name: general-jenkins-dev

services:
  jenkins:
    image: jenkins/jenkins:2.510
    restart: unless-stopped
    user: 
      1000:1000
    ports:
      - "8881:8080"
      - "50000:50000"
    environment:
      # Fixed the quoting issue in JAVA_OPTS
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true -Dhudson.model.DirectoryBrowserSupport.CSP="default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
      - TZ=UTC
      - GIT_REPO_PATH=/mnt/Github
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins_backup:/var/jenkins_backup
      - ${USERPROFILE}/Documents/GitHub:/mnt/Github
    networks:
      - jenkins_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
      

networks:
  jenkins_network:
    driver: bridge

volumes:
  jenkins_home:
    driver: local
  jenkins_backup:
    driver: local